// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurnoverSheetService.Services.DbContextConfiguration;

#nullable disable

namespace TurnoverSheetService.Migrations
{
    [DbContext(typeof(TurnoverSheetDbContext))]
    [Migration("20261009081515_added_unq_indexes_for_saldo")]
    partial class added_unq_indexes_for_saldo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Apartment", b =>
                {
                    b.Property<Guid>("ApartmentGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("address");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("ApartmentGuid")
                        .HasName("apartment_pkey");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("apartments", (string)null);
                });

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Charge", b =>
                {
                    b.Property<Guid>("ChargeUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chargeUUID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("description");

                    b.Property<Guid>("SaldoUuid")
                        .HasColumnType("uuid");

                    b.HasKey("ChargeUuid")
                        .HasName("charges_pkey");

                    b.HasIndex("SaldoUuid");

                    b.ToTable("charges", (string)null);
                });

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Payment", b =>
                {
                    b.Property<Guid>("PaymentUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("paymentUUID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("description");

                    b.Property<Guid>("SaldoUuid")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentUuid")
                        .HasName("payments_pkey");

                    b.HasIndex("SaldoUuid");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Saldo", b =>
                {
                    b.Property<Guid>("SaldoUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("saldoUUID");

                    b.Property<Guid>("ApartmentUuid")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CalculatingDate")
                        .HasColumnType("date")
                        .HasColumnName("calculatingDate");

                    b.Property<decimal>("CurrentSaldoValue")
                        .HasColumnType("numeric")
                        .HasColumnName("сurrentSaldoValue");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("description");

                    b.HasKey("SaldoUuid")
                        .HasName("saldoId_pk");

                    b.HasIndex("ApartmentUuid", "CalculatingDate", "Description")
                        .IsUnique()
                        .HasDatabaseName("idx_saldo_unq");

                    b.ToTable("saldo", (string)null);
                });

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Charge", b =>
                {
                    b.HasOne("TurnoverSheetService.Models.DatabaseEntites.Saldo", "Saldo")
                        .WithMany("Charges")
                        .HasForeignKey("SaldoUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("charges_saldo_fk");

                    b.Navigation("Saldo");
                });

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Payment", b =>
                {
                    b.HasOne("TurnoverSheetService.Models.DatabaseEntites.Saldo", "Saldo")
                        .WithMany("Payments")
                        .HasForeignKey("SaldoUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("payments_appartment_fk");

                    b.Navigation("Saldo");
                });

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Saldo", b =>
                {
                    b.HasOne("TurnoverSheetService.Models.DatabaseEntites.Apartment", "Apartment")
                        .WithMany("Saldos")
                        .HasForeignKey("ApartmentUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("saldo_apartment_fk");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Apartment", b =>
                {
                    b.Navigation("Saldos");
                });

            modelBuilder.Entity("TurnoverSheetService.Models.DatabaseEntites.Saldo", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
