// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurnoverSheetService.Services.DbContextConfiguration;

#nullable disable

namespace TurnoverSheetService.Migrations
{
    [DbContext(typeof(TurnoverSheetDbContext))]
    partial class TurnoverSheetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurnoverSheetService.Models.Charge", b =>
                {
                    b.Property<Guid>("ChargeUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chargeUUID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("apartmentNumber");

                    b.Property<DateOnly>("ChargeDate")
                        .HasColumnType("date")
                        .HasColumnName("chargeDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("description");

                    b.HasKey("ChargeUuid")
                        .HasName("charges_pkey");

                    b.HasIndex("ApartmentNumber", "ChargeDate")
                        .HasDatabaseName("idx_charges");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ApartmentNumber", "ChargeDate"), "btree");

                    b.ToTable("charges", (string)null);
                });

            modelBuilder.Entity("TurnoverSheetService.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("paymentUUID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("apartmentNumber");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("paymentDate");

                    b.HasKey("PaymentUuid")
                        .HasName("payments_pkey");

                    b.HasIndex("ApartmentNumber", "PaymentDate")
                        .HasDatabaseName("idx_payment");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ApartmentNumber", "PaymentDate"), "btree");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("TurnoverSheetService.Models.Saldo", b =>
                {
                    b.Property<Guid>("SaldoUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("saldoUUID");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("apartmentNumber");

                    b.Property<decimal>("CurrentSaldoValue")
                        .HasColumnType("numeric")
                        .HasColumnName("сurrentSaldoValue");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("paymentDate");

                    b.HasKey("SaldoUuid")
                        .HasName("saldoId_pk");

                    b.HasIndex("ApartmentNumber", "PaymentDate")
                        .HasDatabaseName("idx_saldo");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ApartmentNumber", "PaymentDate"), "btree");

                    b.ToTable("saldo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
